version: "3"
services:
  db:
    image: "postgres:latest"
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: afceamgmevent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password